update all products with latest PSU or recommended patches, not just WLS
oracle/weblogic-image-tool pull request #290
Opened 2021-06-29 22:22 UTC by ddsharpe

When looking at the --fromImage, all installed products in the Oracle Home should be considered for patching and latest PSUs.

2021-06-29 22:28 UTC, jshum2479 approved these changes

2021-06-30 14:58 UTC, CarolynRountree requested changes
clarify comment

2021-06-30 14:58 UTC, CarolynRountree commented on imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/FmwInstallerType.java
> +        // create an List from the comma-separated list
comma separated set

2021-07-02 21:10 UTC, CarolynRountree approved these changes

2021-07-06 15:05 UTC, merged