add SPB note
oracle/weblogic-image-tool pull request #329
Opened 2021-12-07 20:54 UTC by rosemarymarano

2021-12-07 20:58 UTC, ddsharpe approved these changes

2021-12-07 22:17 UTC, mriccell requested changes

2021-12-07 22:17 UTC, mriccell commented on documentation/1.10/content/quickstart/prerequisites.md
> +{{% notice note %}} The WebLogic Image Tool does not support a Stack Patch Bundle (SPB; see Doc ID [2764636.1](https://support.oracle.com/rs?type=doc&id=2764636.1)), because an SPB is _not_ a patch b
`create` or `update` commands

2021-12-07 22:17 UTC, mriccell commented on documentation/1.10/content/userguide/tools/update-image.md
> +**NOTE**: The WebLogic Image Tool does not support a Stack Patch Bundle (SPB; see Doc ID [2764636.1](https://support.oracle.com/rs?type=doc&id=2764636.1)), because an SPB is _not_ a patch but a mecha
`update` instead of `create`

2021-12-08 14:02 UTC, mriccell approved these changes

2021-12-08 14:02 UTC, merged